[ci]
runtime = "nix"
runner = "ubuntu-24.04"
workspace = true
with_nextest = true
with_msrv = true
with_audit = true
with_deny = true
with_docs = true
publish_crates = true
provider = "actions"
platform = "github"

[release.signing]
key = "818D507F1E62139F8A17EAA64623DEA06FDACFE1"

[release.github]
repo = "caniko/foundry-circle"
target_branch = "trunk"

[release.artifacts]
runner = "ubuntu-24.04"
nix_bundle_attrs = ["release-bundle"]
version_attr = "foundry-circle"
checksum_globs = ["*.tar.gz"]
sign = false
